Features/frontend auth
maver1cus/planner pull request #4
Opened 2022-01-18 20:16 UTC by maver1cus

2022-01-24 08:31 UTC, kicumkicum requested changes
Очень круто! Код крутой и аккуратный. Проблем в нем минимум

2022-01-24 08:31 UTC, kicumkicum commented on apps/api/src/main.ts
> +    origin: 'http://localhost:3000',
По идее, хост и порт стоит держать в константах. Если они где-то используются для старта сервера, то имеет смысл использовать именно их. Тогда их изменение будет отражаться ни на настройке корс.

2022-01-24 08:31 UTC, kicumkicum commented on apps/client/package.json
> +    "redux-devtools-extension": "^2.13.9",
Лучше зафиксировать версию. Вообще узнал недавно, что можно добавить что-то в `.npmrc` проекта и тогда при установке версии будут всегда зафиксированы

2022-01-24 08:31 UTC, kicumkicum commented on apps/client/src/App.tsx
> +import { Layout } from 'antd';
Тут есть пробелы, а выше нет. Линтер это не проверяет? Или не стартует автоматически?

2022-01-24 08:31 UTC, kicumkicum commented on apps/client/src/api/index.ts
> +  const token = localStorage.getItem('token') || '';
Не стоит напрямую обращаться к `localStorage` в проекте. Имеет смысл добавить обертку. Так проще контролировать обращение к хранилищу, логировать в случае отладки, возвращать более удобные дефолтные значения

2022-01-24 08:31 UTC, kicumkicum commented on apps/client/src/components/nav-bar/nav-bar.module.css
> +}
Тут и ниже нет переноса в конце файла

2022-01-24 08:31 UTC, kicumkicum commented on apps/client/src/utils/user.ts
> +  localStorage.setItem('auth', 'true');
Это свойство кажется избыточным. И как будто бы дырой в логике или безопасности. Условно, если в девтулзах выставить ее в `true` даже без токена и логина, то может так получиться, что увидишь что-то интересное. 

Правильнее кажется, вычислять это свойство на основе токена

2022-01-26 13:58 UTC, maver1cus commented on apps/client/package.json
> +    "redux-devtools-extension": "^2.13.9",
done

2022-01-26 13:58 UTC, maver1cus commented on apps/client/src/App.tsx
> +import { Layout } from 'antd';
done

2022-01-27 03:53 UTC, maver1cus commented on apps/client/src/App.tsx
> +import { Layout } from 'antd';
done

2022-01-27 03:53 UTC, maver1cus commented on apps/api/src/main.ts
> +    origin: 'http://localhost:3000',
done

2022-01-27 03:53 UTC, maver1cus commented on apps/client/src/utils/user.ts
> +  localStorage.setItem('auth', 'true');
done

2022-01-27 04:06 UTC, maver1cus commented on apps/client/src/components/nav-bar/nav-bar.module.css
> +}
done

2022-01-31 12:40 UTC, kicumkicum approved these changes
🚀

2022-01-31 12:40 UTC, merged