Refactor/update dependencies api
maver1cus/planner pull request #7
Opened 2023-01-28 16:07 UTC by maver1cus

2023-01-31 15:59 UTC, kicumkicum requested changes
Круто! Комментарии так, по мелочи

2023-01-31 15:59 UTC, kicumkicum commented on apps/backend/src/config/typeorm.config-migrations.ts
> +import { dataSourceOptions } from './typeorm.config';
Коммент не к имкорту, а к имени файла `apps/backend/src/config/typeorm.config-migrations.ts`. Это какое-то требование для такого суффикса `config-migrations`? Если нет, то я бы предложил `typeorm.migrations.config.ts` или `typeorm.config.migrations.ts` или `typeorm-migrations.config.ts`.

Потому что больше суффикса `config-migrations` нигде в коде не встретишь, а `migrations` или `config` вполне

2023-01-31 15:59 UTC, kicumkicum commented on apps/backend/src/config/typeorm.config.ts
> +  port: +process.env.DB_PORT,
Для преобразования в число лучше использовать `Number` или `panseInt`. Они более заметны

2023-01-31 15:59 UTC, kicumkicum commented on apps/backend/src/main.ts
> +    credentials: false,
А почему это поменялось?

2023-01-31 15:59 UTC, kicumkicum commented on apps/backend/src/user/decorators/user.decorator.ts
> +export const User = createParamDecorator(
Круть. Обязательно запиши себе в резюме куда-нибудь, что работаешь с декораторами. Кроме шуток. Повышает уважение

2023-01-31 15:59 UTC, kicumkicum commented on apps/backend/src/user/user.controller.ts
> +    console.log(42);
```suggestion
```

2023-01-31 15:59 UTC, kicumkicum commented on apps/client/src/api/index.ts
> +import { storage } from "../utils/storage";
А в коде выше одинарные кавычки. Нужен линтер

2023-02-08 09:39 UTC, maver1cus commented on apps/backend/package.json
> +    "typeorm": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli -d src/config/typeorm.config.ts",
fix

2023-02-08 09:49 UTC, maver1cus commented on apps/backend/package.json
> +  "jest": {
done

2023-02-08 09:52 UTC, maver1cus commented on apps/backend/src/config/typeorm.config-migrations.ts
> +import { dataSourceOptions } from './typeorm.config';
done

2023-09-04 15:06 UTC, kicumkicum requested changes
Ну нормас! Хороший объем))

2023-09-04 15:06 UTC, kicumkicum commented on apps/web/.eslintignore
> +build
Нужна пустая строка
```suggestion
build

```

2023-09-04 15:06 UTC, kicumkicum commented on apps/web/coverage/lcov-report/sorter.js
> +var addSorting = (function() {
А что за код в этом модуле?

2023-09-04 15:06 UTC, kicumkicum commented on apps/backend/src/main.ts
> +    origin: 'http://localhost:5173',
А что это за порт?

2023-09-04 15:06 UTC, kicumkicum commented on apps/backend/src/config/typeorm.config.ts
> +  database: process.env.DB_DATABASE,
Я бы предложил делать разбор `process.env` в отдельном модуле. Он становится отличным представлением о системе, какие в ней есть сервисы

2023-09-11 19:53 UTC, maver1cus commented on apps/web/config/build/buildDevServer.ts
> +import type { Configuration as DevServerConfiguration } from 'webpack-dev-server';
done

2023-09-11 19:53 UTC, maver1cus commented on apps/web/config/build/buildDevServer.ts
> +import type { BuildOptions } from './types/config';
done

2023-09-11 19:53 UTC, maver1cus commented on apps/web/.eslintignore
> +build
done

2023-09-11 19:54 UTC, maver1cus commented on apps/web/coverage/lcov-report/sorter.js
> +var addSorting = (function() {
удалил и добавил в gitignore

2023-09-11 19:57 UTC, maver1cus commented on apps/backend/src/config/typeorm.config.ts
> +  database: process.env.DB_DATABASE,
done

2023-09-18 21:48 UTC, kicumkicum approved these changes
🚀

2023-09-18 21:48 UTC, merged