Изменяет orm с typeorm на prisma
maver1cus/planner pull request #9
Opened 2023-12-24 16:38 UTC by maver1cus

2024-01-17 17:04 UTC, kicumkicum requested changes

2024-01-17 17:04 UTC, kicumkicum commented on apps/backend/src/user/user.service.ts
> +    console.log(user);
В целом, рекомендую логи писать, но информативные и не просто `console.log`ом. Хотя бы функцией оберткой для него

2024-01-17 17:04 UTC, kicumkicum commented on apps/backend/src/user/user.service.ts
> +      this.configService.get('JWT_SECRET'),
Ну вот да, пошло дублирование строк)

2024-01-27 18:56 UTC, maver1cus commented on apps/backend/src/user/middleware/auth.middleware.ts
> +        const { id } = verify(token, this.configService.get('JWT_SECRET')) as {
done

2024-01-27 18:56 UTC, maver1cus commented on apps/backend/src/user/user.service.ts
> +      this.configService.get('JWT_SECRET'),
done

2024-02-03 21:50 UTC, maver1cus commented on apps/backend/package.json
> +    "db:migration:prod": "npx prisma migrate build"
done

2024-02-03 22:03 UTC, maver1cus commented on apps/backend/src/user/user.service.ts
> +    prisma: PrismaService,
свойство prisma не публичное, оно нужно для сужения типа PrismaService, который приходит параметром в конструктор он без модификаторов , что ts создавал поле. Свойство переименовал в prismaUserService, что бы не путаться что есть что

2024-02-03 22:04 UTC, maver1cus commented on apps/backend/package.json
> +    "db:migration:prod": "npx prisma migrate build"
done

2024-02-03 22:05 UTC, maver1cus commented on apps/backend/src/user/user.service.ts
> +    console.log(user);
Это я дебажил забыл удалить, логер потом подключу отдельным модулем

2024-02-04 12:50 UTC, kicumkicum requested changes

2024-02-04 12:50 UTC, kicumkicum commented on apps/backend/src/user/user.service.ts
> +  generateJwt(user: User): string {
А `User` это что за сущность?

2024-02-28 17:42 UTC, merged